(^|)adtago\.s3\.amazonaws\.com$
(^|)m\.doubleclick\.net$
(^|)pagead2\.googlesyndication\.com$
(^|)adservice\.google\.com$
(^|)pagead2\.googleadservices\.com$
(^|)afs\.googlesyndication\.com$
(^|)stats\.g\.doubleclick\.net$
(^|)ad\.doubleclick\.net$
(^|)static\.doubleclick\.net$
(^|)analyticsengine\.s3\.amazonaws\.com$
(^|)mediavisor\.doubleclick\.net$
(^|)ads30\.adcolony\.com$
(^|)adc3-launch\.adcolony\.com$
(^|)events3alt\.adcolony\.com$
(^|)wd\.adcolony\.com$
(^|)static\.media\.net$
(^|)media\.net$
(^|)adservetx\.media\.net$
(^|)google-analytics\.com$
(^|)ssl\.google-analytics\.com$
(^|)adm\.hotjar\.com$
(^|)identify\.hotjar\.com$
(^|)insights\.hotjar\.com$
(^|)script\.hotjar\.com$
(^|)surveys\.hotjar\.com$
(^|)careers\.hotjar\.com$
(^|)mouseflow\.com$
(^|)api\.mouseflow\.com$
(^|)tools\.mouseflow\.com$
(^|)cdn-test\.mouseflow\.com$
(^|)luckyorange\.com$
(^|)api\.luckyorange\.com$
(^|)realtime\.luckyorange\.com$
(^|)cdn\.luckyorange\.com$
(^|)w1\.luckyorange\.com$
(^|)upload\.luckyorange\.net$
(^|)cs\.luckyorange\.net$
(^|)settings\.luckyorange\.net$
(^|)pixel\.facebook\.com$
(^|)an\.facebook\.com$
(^|)static\.ads-twitter\.com$
(^|)ads-api\.twitter\.com$
(^|)ads\.yahoo\.com$
(^|)analytics\.yahoo\.com$
(^|)advertising\.yahoo\.com$
(^|)adfox\.yandex\.ru$
(^|)samsung-com\.112\.2o7\.net$
(^|)analytics\.s3\.amazonaws\.com$
(^|)advice-ads\.s3\.amazonaws\.com$
(^|)advertising-api-eu\.amazon\.com$
(^|)app-measurement\.com$
(^|)click\.googleanalytics\.com$
(^|)claritybt\.freshmarketer\.com$
(^|)analytics\.google\.com$
(^|)events\.hotjar\.io$
(^|)fwtracks\.freshmarketer\.com$
(^|)stats\.wp\.com$
(^|)notify\.bugsnag\.com$
(^|)sessions\.bugsnag\.com$
(^|)api\.bugsnag\.com$
(^|)app\.bugsnag\.com$
(^|)app\.getsentry\.com$
(^|)ads\.linkedin\.com$
(^|)ads\.pinterest\.com$
(^|)browser\.sentry-cdn\.com$
(^|)log\.pinterest\.com$
(^|)analytics\.pinterest\.com$
(^|)trk\.pinterest\.com$
(^|)widgets\.pinterest\.com$
(^|)events\.reddit\.com$
(^|)events\.redditmedia\.com$
(^|)ads-api\.tiktok\.com$
(^|)ads\.youtube\.com$
(^|)analytics\.tiktok\.com$
(^|)ads-sg\.tiktok\.com$
(^|)log\.byteoversea\.com$
(^|)business-api\.tiktok\.com$
(^|)analytics-sg\.tiktok\.com$
(^|)ads\.tiktok\.com$
(^|)geo\.yahoo\.com$
(^|)udc\.yahoo\.com$
(^|)advertising\.apple\.com$
(^|)api-adservices\.apple\.com$
(^|)books-analytics-events\.apple\.com$
(^|)freshmarketer\.com$
(^|)log\.fc\.yahoo\.com$
(^|)udcm\.yahoo\.com$
(^|)iadsdk\.apple\.com$
(^|)analytics\.query\.yahoo\.com$
(^|)adserver\.unityads\.unity3d\.com$
(^|)api\.ad\.xiaomi\.com$
(^|)iot-eu-logser\.realme\.com$
(^|)metrics\.icloud\.com$
(^|)metrics\.mzstatic\.com$
(^|)metrika\.yandex\.ru$
(^|)notes-analytics-events\.apple\.com$
(^|)adfstat\.yandex\.ru$
(^|)globalapi\.ad\.xiaomi\.com$
(^|)metrics\.apple\.com$
(^|)grs\.hicloud\.com$
(^|)extmaps-api\.yandex\.net$
(^|)logbak\.hicloud\.com$
(^|)tr\.iadsdk\.apple\.com$
(^|)metrics2\.data\.hicloud\.com$
(^|)weather-analytics-events\.apple\.com$
(^|)data\.mistat\.rus\.xiaomi\.com$
(^|)offerwall\.yandex\.net$
(^|)metrics\.data\.hicloud\.com$
(^|)logservice\.hicloud\.com$
(^|)smetrics\.samsung\.com$
(^|)partnerads\.ysm\.yahoo\.com$
(^|)data\.mistat\.india\.xiaomi\.com$
(^|)open\.oneplus\.net$
(^|)data\.mistat\.xiaomi\.com$
(^|)bdapi-in-ads\.realmemobile\.com$
(^|)nmetrics\.samsung\.com$
(^|)webview\.unityads\.unity3d\.com$
(^|)config\.unityads\.unity3d\.com$
(^|)gemini\.yahoo\.com$
(^|)adtech\.yahooinc\.com$
(^|)auction\.unityads\.unity3d\.com$
(^|)iot-logser\.realme\.com$
(^|)sdkconfig\.ad\.intl\.xiaomi\.com$
(^|)sdkconfig\.ad\.xiaomi\.com$
(^|)adx\.ads\.oppomobile\.com$
(^|)analytics-api\.samsunghealthcn\.com$
(^|)analytics\.pointdrive\.linkedin\.com$
(^|)tracking\.rus\.miui\.com$
(^|)adsfs\.oppomobile\.com$
(^|)bdapi-ads\.realmemobile\.com$
(^|)ck\.ads\.oppomobile\.com$
(^|)click\.oneplus\.cn$
(^|)logservice1\.hicloud\.com$
(^|)appmetrica\.yandex\.ru$
(^|)samsungads\.com$
(^|)advertising\.yandex\.ru$
(^|)data\.ads\.oppomobile\.com$
